deepSeek:
  modelName: 'deepseek-chat'
  apiKey: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxx"
  apiBase: "https://api.deepseek.com/v1"
  maxTokens: 1024
  embeddingModelName: 'text-embedding-v4'

qwen:
  modelName: 'qwen-plus'
  apiKey: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  apiBase: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  maxTokens: 1024
  embeddingModelName: 'text-embedding-v4'

chroma:
  host: "192.168.50.109"
  port: 7000
  collection_name: "doc_code_db"

