deepSeek:
  modelName: 'deepseek-chat'
  apiKey: "sk-xxxxxxxxxxxxxxxxx"
  apiBase: "https://api.deepseek.com/v1"
  maxTokens: 1024

qwen:
  modelName: 'qwen-plus'
  apiKey: "sk-xxxxxxxxxxxxxxxxx"
  apiBase: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  maxTokens: 1024